### ISSUE TITLE
Pass validation message into validate macro

### ISSUE THREAD

**Issue by mentalbrew** [Keats/validator#19] opened 2017-02-19 20:03 UTC
I was wondering if it was at all possible to provide a message into the validate macro that could be used when returning a response back to the caller. The caller then could just essentially present the message to the user without needing to "know" the error code. Something like this maybe:

```
#[derive(Validate)]
pub struct Something {
    #[validate(length(min = "3", error="Must be at least 3 characters long"))]
    pub name: String
}
```

I don't know enough about macros 1.1 to know if this is even feasible but it would keep a user friendly error bundled with the validate declaration.

Plausible or not?

**Comment by Keats** [comment] 2017-02-20 02:47
Closing this one as it's a duplicate of https://github.com/Keats/validator/issues/10

I'd be happy to get feedback on #10 !

**Closed by Keats** 2017-02-20 02:47 UTC

**Comment by mentalbrew** [comment] 2017-02-20 03:05
Not sure how I missed that. I even checked the tickets before posting. My apologies!
