### ISSUE TITLE
function to receive validation rules

### ISSUE THREAD

**Issue by incker** [Keats/validator#70] opened 2019-01-21 10:46 UTC
It is not an issue, maybe a feature request

But how can I get validation rules, to use them in frontend (js) ?
Any format of validation rules will suit me.

And if there is a custom validation - I just would like to know that field have custom validation also and that'it

Forward thank you for any your reply

**Comment by Keats** [comment] 2019-01-21 15:53
The first part is a duplicate of https://github.com/Keats/validator/issues/14

Can you expand on the second part?

**Comment by incker** [comment] 2020-02-27 19:53
Never mind. I was too young when I was creating this issue.
Thank you for showing duplicate issue - I was replying there a possible way to make a serializable struct for frontend (javascript)

And I think, I need to close this issue.
And thank you for your crate!) It is helpful

**Closed** 2020-02-27 19:54 UTC
